dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

# Uncomment to upload heapdumps to S3 bucket; https://docs.travis-ci.com/user/uploading-artifacts/
#addons:
#  artifacts:
#    paths:
#      - $(ls $HOME/build/mjiderhamn/classloader-leak-prevention/classloader-leak-prevention/classloader-leak-prevention-core/target/surefire-reports/*.hprof | tr "\n" ":")
